# Generated by Django 5.2.3 on 2025-06-22 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Odoo SaaS 管理平台', max_length=100, verbose_name='站点名称')),
                ('site_description', models.TextField(default='用于管理 Odoo SaaS 部署的管理平台', verbose_name='站点描述')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='管理员邮箱')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='维护模式')),
                ('max_upload_size', models.IntegerField(default=50, verbose_name='最大上传大小(MB)')),
                ('session_timeout', models.IntegerField(default=1440, verbose_name='会话超时时间(分钟)')),
                ('backup_enabled', models.BooleanField(default=True, verbose_name='启用自动备份')),
                ('backup_frequency', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=10, verbose_name='备份频率')),
                ('log_retention_days', models.IntegerField(default=90, verbose_name='日志保留天数')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='启用邮件通知')),
                ('smtp_host', models.CharField(blank=True, max_length=100, verbose_name='SMTP服务器')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP端口')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='使用TLS加密')),
                ('smtp_username', models.CharField(blank=True, max_length=100, verbose_name='SMTP用户名')),
                ('smtp_password', models.CharField(blank=True, max_length=100, verbose_name='SMTP密码')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
    ]
