# Generated by Django 5.2.3 on 2025-06-21 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True, verbose_name='客户ID')),
                ('name', models.CharField(max_length=100, verbose_name='客户名称')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='公司名称')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('deployment_type', models.CharField(choices=[('online', '在线部署'), ('offline', '离线部署')], default='online', max_length=10, verbose_name='部署类型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('suspended', '暂停'), ('expired', '已过期'), ('trial', '试用')], default='trial', max_length=10, verbose_name='客户状态')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='合同开始日期')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='合同结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_code', models.CharField(max_length=500, unique=True, verbose_name='授权码')),
                ('expire_date', models.DateField(verbose_name='过期日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('max_usage', models.IntegerField(default=1, verbose_name='最大使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_keys', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '授权码',
                'verbose_name_plural': '授权码管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
