# Generated by Django 5.2.3 on 2025-06-21 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_name', models.CharField(max_length=100, verbose_name='Release名称')),
                ('namespace', models.CharField(default='odoo', max_length=50, verbose_name='命名空间')),
                ('domain', models.CharField(max_length=200, verbose_name='访问域名')),
                ('admin_password', models.CharField(max_length=100, verbose_name='管理员密码')),
                ('odoo_version', models.CharField(default='18.0', max_length=20, verbose_name='Odoo版本')),
                ('git_repositories', models.JSONField(default=list, verbose_name='Git仓库配置')),
                ('cpu_limit', models.CharField(default='1000m', max_length=20, verbose_name='CPU限制')),
                ('memory_limit', models.CharField(default='2Gi', max_length=20, verbose_name='内存限制')),
                ('storage_size', models.CharField(default='10Gi', max_length=20, verbose_name='存储大小')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('error', '错误'), ('pending', '部署中'), ('unknown', '未知')], default='pending', max_length=10, verbose_name='运行状态')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='最后健康检查')),
                ('helm_values', models.JSONField(default=dict, verbose_name='Helm Values配置')),
                ('deployed_at', models.DateTimeField(blank=True, null=True, verbose_name='部署时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境管理',
                'ordering': ['-created_at'],
                'unique_together': {('release_name', 'namespace')},
            },
        ),
        migrations.CreateModel(
            name='EnvironmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('deploy', '部署'), ('start', '启动'), ('stop', '停止'), ('update', '更新'), ('delete', '删除'), ('health_check', '健康检查')], max_length=20, verbose_name='操作类型')),
                ('message', models.TextField(verbose_name='日志信息')),
                ('status', models.CharField(max_length=20, verbose_name='操作状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='environments.environment', verbose_name='环境')),
            ],
            options={
                'verbose_name': '环境日志',
                'verbose_name_plural': '环境日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
