# Generated by Django 5.2.3 on 2025-06-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='git_repositories',
        ),
        migrations.AddField(
            model_name='environment',
            name='cpu_request',
            field=models.CharField(default='200m', max_length=20, verbose_name='CPU请求'),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_cpu_limit',
            field=models.CharField(default='500m', max_length=20, verbose_name='数据库CPU限制'),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_cpu_request',
            field=models.CharField(default='100m', max_length=20, verbose_name='数据库CPU请求'),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_enabled',
            field=models.BooleanField(default=True, verbose_name='内置PostgreSQL'),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_filter',
            field=models.CharField(blank=True, max_length=100, verbose_name='数据库过滤器'),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_instances',
            field=models.IntegerField(default=1, verbose_name='数据库实例数'),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_memory_limit',
            field=models.CharField(default='512Mi', max_length=20, verbose_name='数据库内存限制'),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_memory_request',
            field=models.CharField(default='256Mi', max_length=20, verbose_name='数据库内存请求'),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_storage_size',
            field=models.CharField(default='5Gi', max_length=20, verbose_name='数据库存储'),
        ),
        migrations.AddField(
            model_name='environment',
            name='db_version',
            field=models.CharField(default='16', max_length=10, verbose_name='PostgreSQL版本'),
        ),
        migrations.AddField(
            model_name='environment',
            name='external_db_enabled',
            field=models.BooleanField(default=False, verbose_name='使用外部数据库'),
        ),
        migrations.AddField(
            model_name='environment',
            name='external_db_host',
            field=models.CharField(blank=True, max_length=200, verbose_name='外部数据库主机'),
        ),
        migrations.AddField(
            model_name='environment',
            name='external_db_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='外部数据库名'),
        ),
        migrations.AddField(
            model_name='environment',
            name='external_db_port',
            field=models.IntegerField(default=5432, verbose_name='外部数据库端口'),
        ),
        migrations.AddField(
            model_name='environment',
            name='external_db_user',
            field=models.CharField(blank=True, max_length=100, verbose_name='外部数据库用户'),
        ),
        migrations.AddField(
            model_name='environment',
            name='git_customer_addons',
            field=models.JSONField(default=list, verbose_name='客户Addons仓库'),
        ),
        migrations.AddField(
            model_name='environment',
            name='git_odoo_ref',
            field=models.CharField(default='18.0', max_length=100, verbose_name='Odoo分支'),
        ),
        migrations.AddField(
            model_name='environment',
            name='git_odoo_repository',
            field=models.CharField(default='git@github.com:ShanghaiMeowAI/MeowCloud.git', max_length=200, verbose_name='Odoo核心仓库'),
        ),
        migrations.AddField(
            model_name='environment',
            name='git_ssh_secret',
            field=models.CharField(default='global-git-ssh-key', max_length=100, verbose_name='Git SSH密钥'),
        ),
        migrations.AddField(
            model_name='environment',
            name='ingress_class',
            field=models.CharField(default='nginx', max_length=50, verbose_name='Ingress类'),
        ),
        migrations.AddField(
            model_name='environment',
            name='ingress_enabled',
            field=models.BooleanField(default=False, verbose_name='启用Ingress'),
        ),
        migrations.AddField(
            model_name='environment',
            name='ingress_path',
            field=models.CharField(default='/', max_length=100, verbose_name='访问路径'),
        ),
        migrations.AddField(
            model_name='environment',
            name='limit_memory_hard',
            field=models.CharField(default='2684354560', max_length=20, verbose_name='硬内存限制'),
        ),
        migrations.AddField(
            model_name='environment',
            name='limit_memory_soft',
            field=models.CharField(default='2147483648', max_length=20, verbose_name='软内存限制'),
        ),
        migrations.AddField(
            model_name='environment',
            name='limit_request',
            field=models.IntegerField(default=8192, verbose_name='请求限制'),
        ),
        migrations.AddField(
            model_name='environment',
            name='list_db',
            field=models.BooleanField(default=False, verbose_name='显示数据库列表'),
        ),
        migrations.AddField(
            model_name='environment',
            name='log_level',
            field=models.CharField(default='info', max_length=20, verbose_name='日志级别'),
        ),
        migrations.AddField(
            model_name='environment',
            name='memory_request',
            field=models.CharField(default='512Mi', max_length=20, verbose_name='内存请求'),
        ),
        migrations.AddField(
            model_name='environment',
            name='proxy_mode',
            field=models.BooleanField(default=False, verbose_name='代理模式'),
        ),
        migrations.AddField(
            model_name='environment',
            name='storage_auto_expand',
            field=models.BooleanField(default=True, verbose_name='自动扩容'),
        ),
        migrations.AddField(
            model_name='environment',
            name='storage_class',
            field=models.CharField(default='longhorn-expandable', max_length=50, verbose_name='存储类'),
        ),
        migrations.AddField(
            model_name='environment',
            name='storage_expand_size',
            field=models.CharField(default='5Gi', max_length=20, verbose_name='扩容增量'),
        ),
        migrations.AddField(
            model_name='environment',
            name='storage_expand_threshold',
            field=models.IntegerField(default=85, verbose_name='扩容阈值(%)'),
        ),
        migrations.AddField(
            model_name='environment',
            name='storage_max_size',
            field=models.CharField(default='50Gi', max_length=20, verbose_name='最大存储'),
        ),
        migrations.AddField(
            model_name='environment',
            name='tls_enabled',
            field=models.BooleanField(default=False, verbose_name='启用TLS'),
        ),
        migrations.AddField(
            model_name='environment',
            name='tls_secret_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='TLS证书Secret'),
        ),
        migrations.AddField(
            model_name='environment',
            name='workers',
            field=models.IntegerField(default=0, verbose_name='Worker数量'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='domain',
            field=models.CharField(blank=True, max_length=200, verbose_name='访问域名'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='helm_values',
            field=models.JSONField(default=dict, verbose_name='完整Helm Values'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='storage_size',
            field=models.CharField(default='10Gi', max_length=20, verbose_name='Filestore存储大小'),
        ),
    ]
