# Generated by Django 5.2.3 on 2025-06-22 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=200, unique=True, verbose_name='授权码')),
                ('license_type', models.CharField(choices=[('trial', '试用版'), ('standard', '标准版'), ('professional', '专业版'), ('enterprise', '企业版')], default='standard', max_length=20, verbose_name='授权类型')),
                ('max_users', models.IntegerField(default=10, verbose_name='最大用户数')),
                ('max_companies', models.IntegerField(default=1, verbose_name='最大公司数')),
                ('max_storage_gb', models.IntegerField(default=10, verbose_name='最大存储GB')),
                ('modules_enabled', models.JSONField(default=list, verbose_name='启用的模块')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='签发时间')),
                ('valid_from', models.DateTimeField(verbose_name='生效时间')),
                ('valid_until', models.DateTimeField(verbose_name='到期时间')),
                ('status', models.CharField(choices=[('active', '有效'), ('expired', '已过期'), ('revoked', '已撤销'), ('pending', '待激活')], default='pending', max_length=10, verbose_name='状态')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='激活时间')),
                ('last_check', models.DateTimeField(blank=True, null=True, verbose_name='最后检查时间')),
                ('hardware_fingerprint', models.CharField(blank=True, max_length=100, verbose_name='硬件指纹')),
                ('deployment_domain', models.CharField(blank=True, max_length=200, verbose_name='部署域名')),
                ('deployment_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='部署IP')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '授权码',
                'verbose_name_plural': '授权码管理',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generate', '生成'), ('activate', '激活'), ('revoke', '撤销'), ('check', '检查'), ('expire', '过期')], max_length=20, verbose_name='操作类型')),
                ('message', models.TextField(verbose_name='操作信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='licenses.license', verbose_name='授权码')),
            ],
            options={
                'verbose_name': '授权操作日志',
                'verbose_name_plural': '授权操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_users', models.IntegerField(default=0, verbose_name='当前用户数')),
                ('current_companies', models.IntegerField(default=0, verbose_name='当前公司数')),
                ('current_storage_gb', models.FloatField(default=0, verbose_name='当前存储GB')),
                ('access_ip', models.GenericIPAddressField(verbose_name='访问IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='licenses.license', verbose_name='授权码')),
            ],
            options={
                'verbose_name': '授权使用记录',
                'verbose_name_plural': '授权使用记录',
                'ordering': ['-checked_at'],
            },
        ),
    ]
