# Generated by Django 5.2.3 on 2025-06-21 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '登录'), ('logout', '登出'), ('create_customer', '创建客户'), ('update_customer', '更新客户'), ('delete_customer', '删除客户'), ('deploy_environment', '部署环境'), ('start_environment', '启动环境'), ('stop_environment', '停止环境'), ('generate_license', '生成授权码')], max_length=30, verbose_name='操作类型')),
                ('target_type', models.CharField(blank=True, max_length=50, verbose_name='目标类型')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='目标ID')),
                ('description', models.TextField(blank=True, verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('operator', '运维员'), ('viewer', '查看员')], default='viewer', max_length=10, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='部门')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='职位')),
                ('can_manage_customers', models.BooleanField(default=False, verbose_name='可管理客户')),
                ('can_manage_environments', models.BooleanField(default=False, verbose_name='可管理环境')),
                ('can_view_logs', models.BooleanField(default=True, verbose_name='可查看日志')),
                ('can_generate_licenses', models.BooleanField(default=False, verbose_name='可生成授权码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户管理',
            },
        ),
    ]
